# Site settings
title: Luca Grandinetti's Portfolio
description: Data Scientist Consultant | Design and development of machine learning models
keywords: Data Scientist, Data, ML
author: Luca Grandinetti
